apiVersion: apps/v1beta2
kind: Service
apiVersion: v1
metadata:
  name: pesbuk-svc
spec:
  type: LoadBalancer
  selector:
    app: php-sosmed
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-sosmed
spec:
  selector:
    matchLabels:
      app: php-sosmed
  replicas: 1
  template:
    metadata:
      labels:
        app: php-sosmed
    spec:
      containers:
      - name: php-sosmed
        image: sekolahdevopscilsy/php-sosmed
        ports:
        - containerPort: 80
      - name: mysql-sosmed
        image: sekolahdevopscilsy/mysql-sosmed
        ports:
        - containerPort : 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "1234567890"
